init python:
    class Item:
        def __init__(self, name, description, base_value, weight, sprite=None, category="General"):
            self.name = name
            self.description = description
            self.base_value = base_value
            self.weight = weight
            self.sprite = sprite
            self.category = category
            self.quantity = 1
            self.favorite = False

    # Define the items and their categories
    ITEMS = {
        # Testing items
        "apple": Item(name="Apple", description="A juicy red apple.", base_value=2, weight=0.1, sprite="images/ui/icons/Apple.png", category="Food"),
        "bread": Item(name="Bread", description="A loaf of bread.", base_value=3, weight=0.5, sprite="images/ui/icons/Bread.png", category="Food"),
        "strawberry": Item(name="Strawberry", description="A red berry.", base_value=50, weight=5.0, sprite="images/ui/icons/Strawberry.png", category="Weapon"),
        # Raw Materials
        "wood": Item(name="Wood", description="A piece of wood.", base_value=5, weight=1.0, sprite="images/ui/icons/Wood.png", category="Raw Materials"),
        "stone": Item(name="Stone", description="A piece of stone.", base_value=3, weight=1.5, sprite="images/ui/icons/Stone.png", category="Raw Materials"),
        "iron_ore": Item(name="Iron Ore", description="A piece of iron ore.", base_value=10, weight=2.0, sprite="images/ui/icons/Iron_Ore.png", category="Raw Materials"),
        "copper_ore": Item(name="Copper Ore", description="A piece of copper ore.", base_value=8, weight=2.0, sprite="images/ui/icons/Copper_Ore.png", category="Raw Materials"),
        "silver_ore": Item(name="Silver Ore", description="A piece of silver ore.", base_value=15, weight=2.0, sprite="images/ui/icons/Silver_Ore.png", category="Raw Materials"),
        "gold_ore": Item(name="Gold Ore", description="A piece of gold ore.", base_value=20, weight=2.0, sprite="images/ui/icons/Gold_Ore.png", category="Raw Materials"),
        "tar": Item(name="Tar", description="A container of tar.", base_value=7, weight=1.0, sprite="images/ui/icons/Tar.png", category="Raw Materials"),
        "mint": Item(name="Mint", description="A bundle of mint.", base_value=2, weight=0.1, sprite="images/ui/icons/Mint.png", category="Raw Materials"),
        "chamomile": Item(name="Chamomile", description="A bundle of chamomile.", base_value=2, weight=0.1, sprite="images/ui/icons/Chamomile.png", category="Raw Materials"),
        "thyme": Item(name="Thyme", description="A bundle of thyme.", base_value=2, weight=0.1, sprite="images/ui/icons/Thyme.png", category="Raw Materials"),
        "sage": Item(name="Sage", description="A bundle of sage.", base_value=2, weight=0.1, sprite="images/ui/icons/Sage.png", category="Raw Materials"),
        "lavender": Item(name="Lavender", description="A bundle of lavender.", base_value=2, weight=0.1, sprite="images/ui/icons/Lavender.png", category="Raw Materials"),
        "rosemary": Item(name="Rosemary", description="A bundle of rosemary.", base_value=2, weight=0.1, sprite="images/ui/icons/Rosemary.png", category="Raw Materials"),
        "feverfew": Item(name="Feverfew", description="A bundle of feverfew.", base_value=2, weight=0.1, sprite="images/ui/icons/Feverfew.png", category="Raw Materials"),
        "hyssop": Item(name="Hyssop", description="A bundle of hyssop.", base_value=2, weight=0.1, sprite="images/ui/icons/Hyssop.png", category="Raw Materials"),
        "marjoram": Item(name="Marjoram", description="A bundle of marjoram.", base_value=2, weight=0.1, sprite="images/ui/icons/Marjoram.png", category="Raw Materials"),
        "tansy": Item(name="Tansy", description="A bundle of tansy.", base_value=2, weight=0.1, sprite="images/ui/icons/Tansy.png", category="Raw Materials"),
        "yarrow": Item(name="Yarrow", description="A bundle of yarrow.", base_value=2, weight=0.1, sprite="images/ui/icons/Yarrow.png", category="Raw Materials"),
        "parsley": Item(name="Parsley", description="A bundle of parsley.", base_value=2, weight=0.1, sprite="images/ui/icons/Parsley.png", category="Raw Materials"),
        "medicinal_mushroom": Item(name="Medicinal Mushroom", description="A medicinal mushroom.", base_value=5, weight=0.2, sprite="images/ui/icons/Medicinal_Mushroom.png", category="Raw Materials"),
        "sheep_wool": Item(name="Sheep Wool", description="A bundle of sheep wool.", base_value=10, weight=1.0, sprite="images/ui/icons/Sheep_Wool.png", category="Raw Materials"),
        "goat_wool": Item(name="Goat Wool", description="A bundle of goat wool.", base_value=10, weight=1.0, sprite="images/ui/icons/Goat_Wool.png", category="Raw Materials"),
        "rabbit_wool": Item(name="Rabbit Wool", description="A bundle of rabbit wool.", base_value=10, weight=1.0, sprite="images/ui/icons/Rabbit_Wool.png", category="Raw Materials"),
        "clay": Item(name="Clay", description="A piece of clay.", base_value=5, weight=1.5, sprite="images/ui/icons/Clay.png", category="Raw Materials"),
        "salt": Item(name="Salt", description="A bag of salt.", base_value=3, weight=1.0, sprite="images/ui/icons/Salt.png", category="Raw Materials"),
        "metal_scraps": Item(name="Metal Scraps", description="A bundle of metal scraps.", base_value=8, weight=2.0, sprite="images/ui/icons/Metal_Scraps.png", category="Raw Materials"),
        # Crafted Goods
        "ceramic": Item(name="Ceramic", description="A piece of ceramic.", base_value=10, weight=1.0, sprite="images/ui/icons/Ceramic.png", category="Crafted Goods"),
        "coal": Item(name="Coal", description="A piece of coal.", base_value=5, weight=1.0, sprite="images/ui/icons/Coal.png", category="Crafted Goods"),
        "crab_cage": Item(name="Crab Cage", description="A crab cage.", base_value=20, weight=5.0, sprite="images/ui/icons/Crab_Cage.png", category="Crafted Goods"),
        "hunting_trap": Item(name="Hunting Trap", description="A hunting trap.", base_value=15, weight=3.0, sprite="images/ui/icons/Hunting_Trap.png", category="Crafted Goods"),
        "fertilizer": Item(name="Fertilizer", description="A bag of fertilizer.", base_value=8, weight=2.0, sprite="images/ui/icons/Fertilizer.png", category="Crafted Goods"),
        "leather": Item(name="Leather", description="A piece of leather.", base_value=12, weight=1.0, sprite="images/ui/icons/Leather.png", category="Crafted Goods"),
        "glass_bottles": Item(name="Glass Bottles", description="A set of glass bottles.", base_value=10, weight=1.0, sprite="images/ui/icons/Glass_Bottles.png", category="Crafted Goods"),
        "candles": Item(name="Candles", description="A set of candles.", base_value=5, weight=0.5, sprite="images/ui/icons/Candles.png", category="Crafted Goods"),
        "soap": Item(name="Soap", description="A bar of soap.", base_value=3, weight=0.2, sprite="images/ui/icons/Soap.png", category="Crafted Goods"),
        "linen_bolt": Item(name="Linen Bolt", description="A bolt of linen.", base_value=15, weight=1.0, sprite="images/ui/icons/Linen_Bolt.png", category="Crafted Goods"),
        "linen_sack": Item(name="Linen Sack", description="A linen sack.", base_value=5, weight=0.5, sprite="images/ui/icons/Linen_Sack.png", category="Crafted Goods"),
        "copper_ingot": Item(name="Copper Ingot", description="A copper ingot.", base_value=15, weight=2.0, sprite="images/ui/icons/Copper_Ingot.png", category="Crafted Goods"),
        "silver_ingot": Item(name="Silver Ingot", description="A silver ingot.", base_value=20, weight=2.0, sprite="images/ui/icons/Silver_Ingot.png", category="Crafted Goods"),
        "iron_ingot": Item(name="Iron Ingot", description="An iron ingot.", base_value=10, weight=2.0, sprite="images/ui/icons/Iron_Ingot.png", category="Crafted Goods"),
        "bolt_of_cloth": Item(name="Bolt of Cloth", description="A bolt of cloth.", base_value=15, weight=1.0, sprite="images/ui/icons/Bolt_of_Cloth.png", category="Crafted Goods"),
        "rope": Item(name="Rope", description="A length of rope.", base_value=5, weight=2.0, sprite="images/ui/icons/Rope.png", category="Crafted Goods"),
        "clay_pot": Item(name="Clay Pot", description="A clay pot.", base_value=8, weight=1.0, sprite="images/ui/icons/Clay_Pot.png", category="Crafted Goods"),
        "basket": Item(name="Basket", description="A woven basket.", base_value=5, weight=1.0, sprite="images/ui/icons/Basket.png", category="Crafted Goods"),
        "writing_quill": Item(name="Writing Quill", description="A writing quill.", base_value=2, weight=0.1, sprite="images/ui/icons/Writing_Quill.png", category="Crafted Goods"),
        "writing_ink": Item(name="Writing Ink", description="A bottle of writing ink.", base_value=3, weight=0.2, sprite="images/ui/icons/Writing_Ink.png", category="Crafted Goods"),
        "string": Item(name="String", description="A spool of string.", base_value=1, weight=0.1, sprite="images/ui/icons/String.png", category="Crafted Goods"),
        "paper": Item(name="Paper", description="A sheet of paper.", base_value=1, weight=0.1, sprite="images/ui/icons/Paper.png", category="Crafted Goods"),
        "red_dye": Item(name="Red Dye", description="A bottle of red dye.", base_value=5, weight=0.5, sprite="images/ui/icons/Red_Dye.png", category="Crafted Goods"),
        "blue_dye": Item(name="Blue Dye", description="A bottle of blue dye.", base_value=5, weight=0.5, sprite="images/ui/icons/Blue_Dye.png", category="Crafted Goods"),
        "yellow_dye": Item(name="Yellow Dye", description="A bottle of yellow dye.", base_value=5, weight=0.5, sprite="images/ui/icons/Yellow_Dye.png", category="Crafted Goods"),
        "green_dye": Item(name="Green Dye", description="A bottle of green dye.", base_value=5, weight=0.5, sprite="images/ui/icons/Green_Dye.png", category="Crafted Goods"),
        "purple_dye": Item(name="Purple Dye", description="A bottle of purple dye.", base_value=5, weight=0.5, sprite="images/ui/icons/Purple_Dye.png", category="Crafted Goods"),
        "orange_dye": Item(name="Orange Dye", description="A bottle of orange dye.", base_value=5, weight=0.5, sprite="images/ui/icons/Orange_Dye.png", category="Crafted Goods"),
        "black_dye": Item(name="Black Dye", description="A bottle of black dye.", base_value=5, weight=0.5, sprite="images/ui/icons/Black_Dye.png", category="Crafted Goods"),
        "white_dye": Item(name="White Dye", description="A bottle of white dye.", base_value=5, weight=0.5, sprite="images/ui/icons/White_Dye.png", category="Crafted Goods"),
        "brown_dye": Item(name="Brown Dye", description="A bottle of brown dye.", base_value=5, weight=0.5, sprite="images/ui/icons/Brown_Dye.png", category="Crafted Goods"),
        # Foodstuffs
        "wheat": Item(name="Wheat", description="A bundle of wheat.", base_value=3, weight=1.0, sprite="images/ui/icons/Wheat.png", category="Foodstuffs"),
        "barley": Item(name="Barley", description="A bundle of barley.", base_value=3, weight=1.0, sprite="images/ui/icons/Barley.png", category="Foodstuffs"),
        "rye": Item(name="Rye", description="A bundle of rye.", base_value=3, weight=1.0, sprite="images/ui/icons/Rye.png", category="Foodstuffs"),
        "carrots": Item(name="Carrots", description="A bundle of carrots.", base_value=2, weight=0.5, sprite="images/ui/icons/Carrots.png", category="Foodstuffs"),
        "potatoes": Item(name="Potatoes", description="A bundle of potatoes.", base_value=2, weight=1.0, sprite="images/ui/icons/Potatoes.png", category="Foodstuffs"),
        "cabbages": Item(name="Cabbages", description="A bundle of cabbages.", base_value=2, weight=1.0, sprite="images/ui/icons/Cabbages.png", category="Foodstuffs"),
        "apples": Item(name="Apples", description="A bundle of apples.", base_value=2, weight=1.0, sprite="images/ui/icons/Apples.png", category="Foodstuffs"),
        "berries": Item(name="Berries", description="A bundle of berries.", base_value=2, weight=0.5, sprite="images/ui/icons/Berries.png", category="Foodstuffs"),
        "poultry": Item(name="Poultry", description="A piece of poultry.", base_value=5, weight=1.0, sprite="images/ui/icons/Poultry.png", category="Foodstuffs"),
        "beef": Item(name="Beef", description="A piece of beef.", base_value=8, weight=1.5, sprite="images/ui/icons/Beef.png", category="Foodstuffs"),
        "pork": Item(name="Pork", description="A piece of pork.", base_value=7, weight=1.5, sprite="images/ui/icons/Pork.png", category="Foodstuffs"),
        "fish": Item(name="Fish", description="A piece of fish.", base_value=5, weight=1.0, sprite="images/ui/icons/Fish.png", category="Foodstuffs"),
        "dried_fish": Item(name="Dried Fish", description="A piece of dried fish.", base_value=6, weight=0.5, sprite="images/ui/icons/Dried_Fish.png", category="Foodstuffs"),
        "dried_meat": Item(name="Dried Meat", description="A piece of dried meat.", base_value=6, weight=0.5, sprite="images/ui/icons/Dried_Meat.png", category="Foodstuffs"),
        "sausages": Item(name="Sausages", description="A string of sausages.", base_value=5, weight=0.5, sprite="images/ui/icons/Sausages.png", category="Foodstuffs"),
        "chicken_eggs": Item(name="Chicken Eggs", description="A bundle of chicken eggs.", base_value=3, weight=0.5, sprite="images/ui/icons/Chicken_Eggs.png", category="Foodstuffs"),
        "edible_mushrooms": Item(name="Edible Mushrooms", description="A bundle of edible mushrooms.", base_value=4, weight=0.5, sprite="images/ui/icons/Edible_Mushrooms.png", category="Foodstuffs"),
        "lard": Item(name="Lard", description="A container of lard.", base_value=5, weight=1.0, sprite="images/ui/icons/Lard.png", category="Foodstuffs"),
        "butter": Item(name="Butter", description="A container of butter.", base_value=4, weight=1.0, sprite="images/ui/icons/Butter.png", category="Foodstuffs"),
        "vinegar": Item(name="Vinegar", description="A bottle of vinegar.", base_value=3, weight=1.0, sprite="images/ui/icons/Vinegar.png", category="Foodstuffs"),
        "wheat_bread": Item(name="Wheat Bread", description="A loaf of wheat bread.", base_value=5, weight=0.5, sprite="images/ui/icons/Wheat_Bread.png", category="Foodstuffs"),
        "barley_bread": Item(name="Barley Bread", description="A loaf of barley bread.", base_value=5, weight=0.5, sprite="images/ui/icons/Barley_Bread.png", category="Foodstuffs"),
        "rye_bread": Item(name="Rye Bread", description="A loaf of rye bread.", base_value=5, weight=0.5, sprite="images/ui/icons/Rye_Bread.png", category="Foodstuffs"),
        "cheese": Item(name="Cheese", description="A wheel of cheese.", base_value=10, weight=1.0, sprite="images/ui/icons/Cheese.png", category="Foodstuffs"),
        "aged_cheese": Item(name="Aged Cheese", description="A wheel of aged cheese.", base_value=15, weight=1.0, sprite="images/ui/icons/Aged_Cheese.png", category="Foodstuffs"),
        "poor_wine": Item(name="Poor Wine", description="A bottle of poor wine.", base_value=5, weight=1.0, sprite="images/ui/icons/Poor_Wine.png", category="Foodstuffs"),
        "quality_wine": Item(name="Quality Wine", description="A bottle of quality wine.", base_value=15, weight=1.0, sprite="images/ui/icons/Quality_Wine.png", category="Foodstuffs"),
        "wine": Item(name="Wine", description="A bottle of wine.", base_value=10, weight=1.0, sprite="images/ui/icons/Wine.png", category="Foodstuffs"),  
        "beer": Item(name="Beer", description="A bottle of beer.", base_value=3, weight=1.0, sprite="images/ui/icons/Beer.png", category="Foodstuffs"),
        "brandy": Item(name="Brandy", description="A bottle of brandy.", base_value=10, weight=1.0, sprite="images/ui/icons/Brandy.png", category="Foodstuffs"),
        "mead": Item(name="Mead", description="A bottle of mead.", base_value=8, weight=1.0, sprite="images/ui/icons/Mead.png", category="Foodstuffs"),
        "schnapps": Item(name="Schnapps", description="A bottle of schnapps.", base_value=12, weight=1.0, sprite="images/ui/icons/Schnapps.png", category="Foodstuffs"),
        "spices": Item(name="Spices", description="A bundle of spices.", base_value=5, weight=0.5, sprite="images/ui/icons/Spices.png", category="Foodstuffs"),
        "garlic": Item(name="Garlic", description="A bundle of garlic.", base_value=2, weight=0.5, sprite="images/ui/icons/Garlic.png", category="Foodstuffs"),
        "onions": Item(name="Onions", description="A bundle of onions.", base_value=2, weight=0.5, sprite="images/ui/icons/Onions.png", category="Foodstuffs"),
        # Tools & Equipment
        "horse_saddle": Item(name="Horse Saddle", description="A horse saddle.", base_value=20, weight=5.0, sprite="images/ui/icons/Horse_Saddle.png", category="Tools & Equipment"),
        "ormro_saddle": Item(name="Ormro Saddle", description="An ormro saddle.", base_value=25, weight=5.0, sprite="images/ui/icons/Ormro_Saddle.png", category="Tools & Equipment"),
        "animal_feed": Item(name="Animal Feed", description="A bag of animal feed.", base_value=5, weight=10.0, sprite="images/ui/icons/Animal_Feed.png", category="Tools & Equipment"),
        "fishing_net": Item(name="Fishing Net", description="A fishing net.", base_value=15, weight=3.0, sprite="images/ui/icons/Fishing_Net.png", category="Tools & Equipment"),
        "cooking_pot": Item(name="Cooking Pot", description="A cooking pot.", base_value=10, weight=2.0, sprite="images/ui/icons/Cooking_Pot.png", category="Tools & Equipment"),
        "fishing_rod": Item(name="Fishing Rod", description="A fishing rod.", base_value=12, weight=1.5, sprite="images/ui/icons/Fishing_Rod.png", category="Tools & Equipment"),
        "compass": Item(name="Compass", description="A compass.", base_value=8, weight=0.5, sprite="images/ui/icons/Compass.png", category="Tools & Equipment"),
        "sextant": Item(name="Sextant", description="A sextant.", base_value=20, weight=1.0, sprite="images/ui/icons/Sextant.png", category="Tools & Equipment"),
        "barrel": Item(name="Barrel", description="A barrel.", base_value=10, weight=10.0, sprite="images/ui/icons/Barrel.png", category="Tools & Equipment"),
        "pickaxe": Item(name="Pickaxe", description="A pickaxe.", base_value=15, weight=3.0, sprite="images/ui/icons/Pickaxe.png", category="Tools & Equipment"),
        "shovel": Item(name="Shovel", description="A shovel.", base_value=10, weight=2.5, sprite="images/ui/icons/Shovel.png", category="Tools & Equipment"),
        "hammer": Item(name="Hammer", description=  "A hammer.", base_value=8, weight=1.5, sprite="images/ui/icons/Hammer.png", category="Tools & Equipment"),
        "axe": Item(name="Axe", description="An axe.", base_value=12, weight=2.5, sprite="images/ui/icons/Axe.png", category="Tools & Equipment"),
        "clamps": Item(name="Clamps", description="A set of clamps.", base_value=5, weight=1.0, sprite="images/ui/icons/Clamps.png", category="Tools & Equipment"),
        "scythe": Item(name="Scythe", description="A scythe.", base_value=10, weight=2.0, sprite="images/ui/icons/Scythe.png", category="Tools & Equipment"),
        "sickle": Item(name="Sickle", description="A sickle.", base_value=8, weight=1.5, sprite="images/ui/icons/Sickle.png", category="Tools & Equipment"),
        "shears": Item(name="Shears", description="A pair of shears.", base_value=5, weight=1.0, sprite="images/ui/icons/Shears.png", category="Tools & Equipment"),
        # Luxuries
        "bronze_jewelry": Item(name="Bronze Jewelry", description="A piece of bronze jewelry.", base_value=20, weight=0.5, sprite="images/ui/icons/Bronze_Jewelry.png", category="Luxuries"),
        "copper_jewelry": Item(name="Copper Jewelry", description="A piece of copper jewelry.", base_value=25, weight=0.5, sprite="images/ui/icons/Copper_Jewelry.png", category="Luxuries"),
        "silver_jewelry": Item(name="Silver Jewelry", description="A piece of silver jewelry.", base_value=50, weight=0.5, sprite="images/ui/icons/Silver_Jewelry.png", category="Luxuries"),
        "gold_jewelry": Item(name="Gold Jewelry", description="A piece of gold jewelry.", base_value=100, weight=0.5, sprite="images/ui/icons/Gold_Jewelry.png", category="Luxuries"),
        "black_sand": Item(name="Black Sand", description="A bag of black sand.", base_value=15, weight=1.0, sprite="images/ui/icons/Black_Sand.png", category="Luxuries"),
        "rubies": Item(name="Rubies", description="A bundle of rubies.", base_value=200, weight=0.5, sprite="images/ui/icons/Rubies.png", category="Luxuries"),
        "sapphires": Item(name="Sapphires", description="A bundle of sapphires.", base_value=200, weight=0.5, sprite="images/ui/icons/Sapphires.png", category="Luxuries"),
        "pearls": Item(name="Pearls", description="A bundle of pearls.", base_value=150, weight=0.5, sprite="images/ui/icons/Pearls.png", category="Luxuries"),
        "exotic_spices": Item(name="Exotic Spices", description="A bundle of exotic spices.", base_value=30, weight=0.5, sprite="images/ui/icons/Exotic_Spices.png", category="Luxuries"),
        "aged_wine": Item(name="Aged Wine", description="A bottle of aged wine.", base_value=50, weight=1.0, sprite="images/ui/icons/Aged_Wine.png", category="Luxuries"),
        "silk": Item(name="Silk", description="A roll of silk.", base_value=40, weight=1.0, sprite="images/ui/icons/Silk.png", category="Luxuries"),
        "bear_fur": Item(name="Bear Fur", description="A bear fur.", base_value=30, weight=5.0, sprite="images/ui/icons/Bear_Fur.png", category="Luxuries"),
        "wolf_fur": Item(name="Wolf Fur", description="A wolf fur.", base_value=25, weight=3.0, sprite="images/ui/icons/Wolf_Fur.png", category="Luxuries"),
        "wyvern_leather": Item(name="Wyvern Leather", description="A piece of wyvern leather.", base_value=100, weight=2.0, sprite="images/ui/icons/Wyvern_Leather.png", category="Luxuries"),
        "wyvern_scales": Item(name="Wyvern Scales", description="A bundle of wyvern scales.", base_value=150, weight=2.0, sprite="images/ui/icons/Wyvern_Scales.png", category="Luxuries"),
        "lute": Item(name="Lute", description="A lute.", base_value=50, weight=2.0, sprite="images/ui/icons/Lute.png", category="Luxuries"),
        "flute": Item(name="Flute", description="A flute.", base_value=30, weight=0.5, sprite="images/ui/icons/Flute.png", category="Luxuries"),
        "ceramic_furniture": Item(name="Ceramic Furniture", description="A piece of ceramic furniture.", base_value=100, weight=10.0, sprite="images/ui/icons/Ceramic_Furniture.png", category="Luxuries"),
        "convex_glass": Item(name="Convex Glass", description="A piece of convex glass.", base_value=20, weight=1.0, sprite="images/ui/icons/Convex_Glass.png", category="Luxuries"),
        # Components
        "blood_dust": Item(name="Blood Dust", description="A vial of blood dust.", base_value=50, weight=0.5, sprite="images/ui/icons/Blood_Dust.png", category="Components"),
        "wyrm_blood": Item(name="Wyrm Blood", description="A vial of wyrm blood.", base_value=100, weight=0.5, sprite="images/ui/icons/Wyrm_Blood.png", category="Components"),
        "arcane_powder": Item(name="Arcane Powder", description="A vial of arcane powder.", base_value=75, weight=0.5, sprite="images/ui/icons/Arcane_Powder.png", category="Components"),
        "embertree_bark": Item(name="Embertree Bark", description="A piece of embertree bark.", base_value=30, weight=0.5, sprite="images/ui/icons/Embertree_Bark.png", category="Components"),
        # Miscellaneous
        "toys": Item(name="Toys", description="A bundle of toys.", base_value=10, weight=1.0, sprite="images/ui/icons/Toys.png", category="Miscellaneous"),
        "rockmount_souvenirs": Item(name="Rockmount Souvenirs", description="A bundle of Rockmount souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Rockmount_Souvenirs.png", category="Miscellaneous"),
        "aldburg_souvenirs": Item(name="Aldburg Souvenirs", description="A bundle of Aldburg souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Aldburg_Souvenirs.png", category="Miscellaneous"),
        "bormanhold_souvenirs": Item(name="Bormanhold Souvenirs", description="A bundle of Bormanhold souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Bormanhold_Souvenirs.png", category="Miscellaneous"),
        "breezeport_souvenirs": Item(name="Breezeport Souvenirs", description="A bundle of Breezeport souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Breezeport_Souvenirs.png", category="Miscellaneous"),
        "cragbrook_souvenirs": Item(name="Cragbrook Souvenirs", description="A bundle of Cragbrook souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Cragbrook_Souvenirs.png", category="Miscellaneous"),
        "greenwood_souvenirs": Item(name="Greenwood Souvenirs", description="A bundle of Greenwood souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Greenwood_Souvenirs.png", category="Miscellaneous"),
        "lakeborough_souvenirs": Item(name="Lakeborough Souvenirs", description="A bundle of Lakeborough souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Lakeborough_Souvenirs.png", category="Miscellaneous"),
        "rocheguet_souvenirs": Item(name="Rocheguet Souvenirs", description="A bundle of Rocheguet souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Rocheguet_Souvenirs.png", category="Miscellaneous"),
        "sealtharbor_souvenirs": Item(name="Sealtharbor Souvenirs", description="A bundle of Sealtharbor souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Sealtharbor_Souvenirs.png", category="Miscellaneous"),
        "taresfield_souvenirs": Item(name="Taresfield Souvenirs", description="A bundle of Taresfield souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Taresfield_Souvenirs.png", category="Miscellaneous"),
        "weglete_souvenirs": Item(name="Weglete Souvenirs", description="A bundle of Weglete souvenirs.", base_value=5, weight=1.0, sprite="images/ui/icons/Weglete_Souvenirs.png", category="Miscellaneous"),
        "information": Item(name="Information", description="A piece of valuable information.", base_value=50, weight=0.1, sprite="images/ui/icons/Information.png", category="Miscellaneous"),
        }